### ISSUE TITLE
Download button don't save medias anymore

### ISSUE THREAD

**Issue by kervala** [DiVouz/instagram-downloader-extension#1]
Hi,

Your extension is amazing and it worked very well until today :) Thank you so much !

I noticed IG changed their HTML code, the "time" tag is not anymore in a "div" but in a "span" :) Replacing "a:has(div > time)" by "a:has(span > time)" is enough to fix the issue :)

**Comment by DiVouz** [comment]
The issue should be fixed with the latest version, do you still have the issue? @kervala
